export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const REMOVE_COUPON_SUCCESS = 'REMOVE_COUPON_SUCCESS';
export const UPDATE_CART_DETAILS = 'UPDATE_CART_DETAILS';